# Generated by Django 3.1 on 2020-09-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='raw_markdown',
            new_name='body',
        ),
    ]
