# Generated by Django 3.1 on 2020-10-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200916_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_rendered',
            field=models.TextField(default='<p>Test Body </p>'),
            preserve_default=False,
        ),
    ]
