# Generated by Django 3.1 on 2020-10-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_body_rendered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_rendered',
            field=models.TextField(blank=True),
        ),
    ]
