# Generated by Django 3.1 on 2020-10-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201003_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='article-filler'),
            preserve_default=False,
        ),
    ]
