# Generated by Django 3.1 on 2020-10-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
